FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update -y && apt-get install -y mafft && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
# copy private data files into the image (these files are in the repo and the repo is private)
COPY prrsv_scaled_flevo_scores.csv database.fasta /data/
ENV REPO_DATA_DIR=/data
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]